import React from "react";
import { StyleSheet } from "react-native";

export const styles=StyleSheet.create({
    Cont:{
        backgroundColor:"#FFF",
        color:"#ECF0F3",
    },
    divimg:{
        display:"flex",
        alignItems:"center",
        justifyContent:"center",
        overflow:"hidden",
        height:100,
        width:100,
        marginBottom:20,
        borderRadius:500,
        borderColor:"#fff",
        borderWidth:3,
    },
    dv:{
        display:"flex",
        alignItems:"center",
        justifyContent:"center",
    },
    img:{
        height:70,
        borderColor:"#000",
    },
    title:{
        fontSize:40,
        fontWeight:"800",
        textAlign:"center",
        marginBottom:30,
        color:"#168098",
        fontFamily:"Overpass-MediumItalic"
    },
    divlabl:{
        position:"absolute",
        marginBottom:9,
        paddingLeft:65,
        top:23,
        opacity:1,
    },
    diveActivelbl:{
        position:"absolute",
        marginBottom:9,
        paddingLeft:20,
        top:23,
        opacity:0
    },
    labl:{
        fontSize:20,
        fontWeight:"700",
        color:"#627696",
    },
    inputs:{
        borderWidth:2.5,
        fontSize:22,
        padding:11,
        borderRadius:10,
        fontWeight:"500",
        borderColor:"#168098",
        backgroundColor:"#f1fcff",
        color:"#124269",
        paddingLeft:65,
        marginBottom:5,
        marginTop:10,
    },
    errors:{
        marginBottom:4,
        paddingLeft:25,
        fontSize:19,
        color:"red",
        fontWeight:"700"
    },
    ContainerA:{
        flex:1,
        display:"flex",
        justifyContent:"center",
        alignItems:"center",
        position:"absolute",
        top:172,
        paddingTop:50,
        width:405,
        left:0,
        height:520,
        backgroundColor:"#FFF",
    },
    contnn:{
        display:"flex",
        alignItems:"center",
        justifyContent:"center",
        flex:1,
        display:"flex",
        justifyContent:"center",
        alignItems:"center",
        backgroundColor:"#FFF"
    },
    Container:{
        padding:20,
        paddingLeft:30,
        paddingRight:30,
        display:"flex",
        height:540,
        justifyContent:"center",
        alignItems:"center",
        backgroundColor:"#FFF"
    },
    box:{
        position:"relative",
        width:350,
        marginBottom:10
    },
    imgs: {
        width: 35,
        height: 35,
        position:"absolute",
        top:19,left:15,
    },
    btn:{
        padding:10,
        backgroundColor:"#1EA0BD",
        width:250,
        borderRadius:50,
        display:'flex',
        alignItems:'center',
        justifyContent:'center',
    },
    btnText:{
        color:"#ECF0F3",
        fontSize:20,
        fontWeight:"700",
    },
    cont:{
        marginTop:10,
        display:'flex',
        alignItems:'center',
        justifyContent:'center',
    },
    imagediv:{
        display:"flex",
        justifyContent:'center',
        alignItems:'center',
    },
    imh:{
        width:375,
    },
    lik:{
        color:"#168098",
        fontSize:20,
        fontWeight:"700",
        textDecorationLine: 'underline'

    },
    bb:{
        display:"flex",
        alignItems:"center",
        justifyContent:"center",
        marginTop:20
    },
    wave:{
        marginTop:-100
    },
    spca:{
        marginTop:150,
        fontSize:1
    },
    contttt:{
        flex:1,
        display:"flex",
        justifyContent:"center",
        alignItems:"center",
        backgroundColor:"#FFF"
    },
    home:{
        flex:1,
        padding:20,
        width:390,
        backgroundColor:"#FFF",
        display:"flex",
        alignItems:"center"
    },
    imgdv:{
        padding:25,
        borderRadius:80,
        borderWidth:3,
        display:"flex",
        borderColor:"#168098",
        marginBottom:20,
        alignContent:"center",
        alignItems:"center",
        justifyContent:"center",
    },
    imghome:{
        width:40,
        height:40,
        
    },
    btnLogout:{
        padding:10,
        backgroundColor:"#168098",
        width:120,
        display:"flex",
        paddingBottom:12,
        alignItems:"center",
        justifyContent:"center",
        borderRadius:30
    },
    txt:{
        color:"#fff",
        fontSize:20,
        fontWeight:"bold",
    },
    txtus:{
        fontSize:20,
        fontWeight:"700",
        marginBottom:20,
        color:"#168098"
    },
    containerr:{
        width:390,
        borderBottomWidth:2,
        borderBottomColor:"#168098",
        display:"flex",
        padding:10,
        paddingBottom:25,
        justifyContent:"space-around",
        flexDirection: "row",
        flexWrap: "wrap",
        alignItems:"center"
    },
    inf:{
        padding:10,
        display:"flex",
        flexDirection:"column",
        alignItems:"flex-start",
        width:200
    }
});